name: Docker CD

on:
  push:
    branches:
      - main
    paths-ignore: # Prevents unnecessary rebuilds on docs/config changes
      - 'README.md'
      - 'LICENSE'
      - '.github/**'

env:
  # Replace with your Docker Hub or GHCR path (e.g., your-username/fastapi-app)
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/fastapi-app 
  TAG: ${{ github.sha }}

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest
    
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4

      - name: 🐳 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔑 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: 🏗️ Build and push Docker image
        uses: docker/build-and-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest # Always tag with latest
            ${{ env.IMAGE_NAME }}:${{ env.TAG }} # Tag with the unique commit SHA for traceability
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: 🚀 Deploy to production (Optional)
        # This step is placeholder. In a real-world scenario, you would 
        # use actions here to deploy to a platform like Kubernetes, Azure Web Apps, or AWS ECS.
        run: |
          echo "Image ${{ env.IMAGE_NAME }}:${{ env.TAG }} pushed. Ready for deployment."
